//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetLife.web {
    
    
    public partial class Default {
        
        /// <summary>
        /// HighlightsHomePage1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NetLife.web.Controls.Home.HighlightsHomePage HighlightsHomePage1;
        
        /// <summary>
        /// StarCategory1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NetLife.web.Controls.Home.StarCategory StarCategory1;
        
        /// <summary>
        /// CategoryHomePage1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NetLife.web.Controls.Home.StarCategory CategoryHomePage1;
        
        /// <summary>
        /// CategoryHomePage2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NetLife.web.Controls.Home.StarCategory CategoryHomePage2;
        
        /// <summary>
        /// CategoryHomePage3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NetLife.web.Controls.Home.StarCategory CategoryHomePage3;
        
        /// <summary>
        /// CategoryHomePage4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NetLife.web.Controls.Home.StarCategory CategoryHomePage4;
        
        /// <summary>
        /// CategoryHomePage5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NetLife.web.Controls.Home.StarCategory CategoryHomePage5;
        
        /// <summary>
        /// Adv2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NetLife.web.Controls.Advs.Adv Adv2;
        
        /// <summary>
        /// Adv3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NetLife.web.Controls.Advs.Adv Adv3;
        
        /// <summary>
        /// Adv1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NetLife.web.Controls.Advs.Adv Adv1;
        
        /// <summary>
        /// Hot1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NetLife.web.Controls.Lists.Hot Hot1;
        
        /// <summary>
        /// Adv6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NetLife.web.Controls.Advs.Adv Adv6;
        
        /// <summary>
        /// Adv4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NetLife.web.Controls.Advs.Adv Adv4;
        
        /// <summary>
        /// Adv5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NetLife.web.Controls.Advs.Adv Adv5;
        
        /// <summary>
        /// VideoClip1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NetLife.web.Controls.Home.VideoClip VideoClip1;
        
        /// <summary>
        /// Adv7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NetLife.web.Controls.Advs.Adv Adv7;
        
        /// <summary>
        /// Adv8 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NetLife.web.Controls.Advs.Adv Adv8;
    }
}
